'use client';

import { TaxResult } from '@/engine/types';

// Dynamically imported to avoid SSR issues with @react-pdf/renderer
export async function generateTaxPDF(result: TaxResult, premium = false): Promise<void> {
  const { pdf, Document, Page, Text, View, StyleSheet } = await import('@react-pdf/renderer');

  const styles = StyleSheet.create({
    page: { fontFamily: 'Helvetica', padding: 40, fontSize: 10, color: '#1e293b' },
    header: { backgroundColor: '#2563EB', padding: 20, marginBottom: 20, borderRadius: 4 },
    headerTitle: { color: '#ffffff', fontSize: 20, fontFamily: 'Helvetica-Bold' },
    headerSub: { color: '#bfdbfe', fontSize: 10, marginTop: 4 },
    section: { marginBottom: 16 },
    sectionTitle: { fontSize: 12, fontFamily: 'Helvetica-Bold', marginBottom: 8, color: '#1e40af', borderBottom: '1 solid #e2e8f0', paddingBottom: 4 },
    row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottom: '1 solid #f1f5f9' },
    label: { color: '#64748b' },
    value: { fontFamily: 'Helvetica-Bold' },
    valueRed: { fontFamily: 'Helvetica-Bold', color: '#dc2626' },
    valueGreen: { fontFamily: 'Helvetica-Bold', color: '#16a34a' },
    valueBlue: { fontFamily: 'Helvetica-Bold', color: '#2563eb' },
    disclaimer: { marginTop: 20, fontSize: 7, color: '#94a3b8', borderTop: '1 solid #e2e8f0', paddingTop: 8 },
    badge: { backgroundColor: '#eff6ff', padding: '2 6', borderRadius: 4, color: '#1d4ed8', fontSize: 9 },
  });

  const fmt = (n: number) => {
    const sym = result.currency === 'INR' ? '₹' : result.currency === 'USD' ? '$' : '£';
    return `${sym}${Math.round(n).toLocaleString('en-IN')}`;
  };

  const Doc = () => (
    <Document title={`TaxCalc Global — ${result.country} Tax Report`} author="TaxCalc Global">
      {/* Page 1: Summary */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>TaxCalc Global</Text>
          <Text style={styles.headerSub}>
            {result.country === 'IN' ? 'India Income Tax · FY 2025-26' :
             result.country === 'US' ? 'US Income Tax · TY 2025' : 'UK Income Tax · TY 2025-26'}
            {result.regime ? `  ·  ${result.regime === 'new' ? 'New Regime' : 'Old Regime'}` : ''}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Income Summary</Text>
          <View style={styles.row}><Text style={styles.label}>Gross Income</Text><Text style={styles.value}>{fmt(result.grossIncome)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Total Tax</Text><Text style={styles.valueRed}>{fmt(result.totalTax)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Net Income</Text><Text style={styles.valueGreen}>{fmt(result.netIncome)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Monthly Take-Home</Text><Text style={styles.valueGreen}>{fmt(result.monthlyTakeHome)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Effective Tax Rate</Text><Text style={styles.valueBlue}>{(result.effectiveRate * 100).toFixed(2)}%</Text></View>
          <View style={styles.row}><Text style={styles.label}>Marginal Rate</Text><Text style={styles.value}>{(result.marginalRate * 100).toFixed(0)}%</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Tax Breakdown</Text>
          {result.breakdown.map((item) => (
            <View key={item.label} style={styles.row}>
              <Text style={styles.label}>{item.label}</Text>
              <Text style={styles.valueRed}>{fmt(item.amount)}</Text>
            </View>
          ))}
        </View>

        {premium && result.bracketDetails.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Tax by Bracket</Text>
            {result.bracketDetails.map((d, i) => (
              <View key={i} style={styles.row}>
                <Text style={styles.label}>{d.bracket.label || `${(d.bracket.rate * 100).toFixed(0)}%`} bracket</Text>
                <Text style={styles.value}>{fmt(d.taxInThisBracket)}</Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.disclaimer}>
          Generated by TaxCalc Global (taxcalc-global.vercel.app) · For informational purposes only.
          This is not tax advice. Tax laws change — consult a qualified tax professional for your situation.
        </Text>
      </Page>
    </Document>
  );

  const blob = await pdf(<Doc />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `taxcalc-${result.country.toLowerCase()}-report.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
